# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: lint.sh
        language: script
        pass_filenames: false
        always_run: true
      - id: black 
        name: black
        entry: black
        language: system
        types: [python]
      - id: isort 
        name: isort
        entry: isort
        language: system
        types: [python]
      - id: test 
        name: test
        entry: test.sh
        language: script
        pass_filenames: false
        always_run: true
